// Autogenerated from Pigeon (v22.4.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class GeneratedSwiftPerimeterxFlutterPigeonCodecReader: FlutterStandardReader {
}

private class GeneratedSwiftPerimeterxFlutterPigeonCodecWriter: FlutterStandardWriter {
}

private class GeneratedSwiftPerimeterxFlutterPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GeneratedSwiftPerimeterxFlutterPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GeneratedSwiftPerimeterxFlutterPigeonCodecWriter(data: data)
  }
}

class GeneratedSwiftPerimeterxFlutterPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GeneratedSwiftPerimeterxFlutterPigeonCodec(readerWriter: GeneratedSwiftPerimeterxFlutterPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PerimeterxHostApi {
  func getPerimeterxHeaders() throws -> [String: String]
  func handlePerimeterxResponse(response: String, url: String?, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PerimeterxHostApiSetup {
  static var codec: FlutterStandardMessageCodec { GeneratedSwiftPerimeterxFlutterPigeonCodec.shared }
  /// Sets up an instance of `PerimeterxHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PerimeterxHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPerimeterxHeadersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.perimeterx_flutter_plugin.PerimeterxHostApi.getPerimeterxHeaders\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPerimeterxHeadersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPerimeterxHeaders()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPerimeterxHeadersChannel.setMessageHandler(nil)
    }
    let handlePerimeterxResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.perimeterx_flutter_plugin.PerimeterxHostApi.handlePerimeterxResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePerimeterxResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let responseArg = args[0] as! String
        let urlArg: String? = nilOrValue(args[1])
        api.handlePerimeterxResponse(response: responseArg, url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handlePerimeterxResponseChannel.setMessageHandler(nil)
    }
  }
}
